### ISSUE TITLE
Nested Models not identified

### ISSUE THREAD

**Issue by wp4nuv** [dmeybohm/chocolate-cakephp#58]
When making a call to a model method, say, `$this->LoanApplications->find(1);`, the plugin works as advertised, but when making it as a nested call like `$this->LoanApplications->LenderEntityRole->find(1);` the plugin doesn't recognize the `LenderEntityRole` model. Is this something that, perhaps, annotations may help?

**Comment by dmeybohm** [comment]
@wp4nuv Thanks for opening this issue. 

Yes, you're right that the plugin only goes one level deep on the completion, because that was the simplest and most performant implementation. I think I may know a good way of implementing this though, so I'll try to incorporate that into the next version.

In the meantime, I think you can annotate the `LoanApplications` model with `@property LenderEntityRole $LenderEntityRole`. Could you let me know if that doesn't work.

**Comment by dmeybohm** [comment]
I implemented something to handle this in https://github.com/dmeybohm/chocolate-cakephp/pull/63
