### ISSUE TITLE
Chocolate CakePHP incompatible with version 2022.1

### ISSUE THREAD

**Issue by wp4nuv** [dmeybohm/chocolate-cakephp#67]
Just came across this warning after upgrading PhpStorm.  Regardless, the plugin loads (at least I think it does). My guess it's probably a plugin packaging that needs updating. I can look in the code and submit a PR for it, unless you want to check if there is any breaking changes on this new version.

**Comment by dmeybohm** [comment]
@wp4nuv Thanks for letting me know. I went ahead and fixed it, but in retrospect, I would have appreciated a PR .

The main problem was the version in the `plugin.xml`, so it would have been simple to update. However, there was another issue where the tests were failing after I updated it. The issue seemed to be that at least one test had to have the annotation or otherwise the tests were being skipped altogether. I fixed it in this PR: https://github.com/dmeybohm/chocolate-cakephp/pull/68
